swagger: '2.0'
info:
  description: Wägeschein Service für Prozesse, die mit Wägungen zu tun haben.
  version: 0.0.2
  title: weighing-service
basePath: /api/
tags:
- name: weighing
  description: Waagen und Wägescheine
schemes:
- http
paths:
  /branches:
    get:
      tags:
      - branches
      summary: Abfragen der Niederlassungen
      description: Gibt die Liste aller Niederlassungen zurück.
      operationId: getBranches
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: page
        in: query
        description: Seitennummer (0-basiert)
        required: false
        type: integer
        format: int64
      - name: size
        in: query
        description: Anzahl der Ergebnisse, die angezeigt werden sollen.
        required: false
        type: integer
        format: int64
      - name: sort
        in: query
        description: 'Reihenfolge der Ergebnisse, per Spaltenname. Kann jeweils pro
          Datenbank-Spalte angegeben werden: z.B. sort=name,asc&sort=id,desc'
        pattern: '[a-zA-Z]+(,asc|,desc)?'
        required: false
        type: string
      responses:
        '200':
          description: (Status OK) Liste von Niederlassungen
          schema:
            type: array
            items:
              $ref: '#/definitions/BranchPage'
  /weighing-note:
    post:
      tags:
      - weighing
      summary: Erstellung eines Wägescheins
      description: Erstellt ein Wägeschein im PDF/A-3 Format. Siehe https://jira.remondis-de.local/browse/RENEW-437
      operationId: createWeighingNote
      consumes:
      - application/json
      produces:
      - application/pdf
      parameters:
      - in: body
        name: weighingNote
        description: Wägeschein-Daten
        required: true
        schema:
          $ref: '#/definitions/WeighingNote'
      responses:
        '200':
          description: (Status OK) Generiertes PDF Dokument
          schema:
            type: file
  /weighing-devices/{id}/weighing:
    post:
      tags:
      - weighing
      - weighing-devices
      summary: Erzeugung einer neuen Wägung für die angegebene Waage.
      description: Die Erzeugung einer neuen Wägung für die angegebene Waage kann über diese Service-URL angefragt werden.
      parameters:
      - name: id
        in: path
        description: ID der Waage
        required: true
        type: integer
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/WeighingData'
        '404':
          description: Waage nicht gefunden
  /weighing-devices:
    get:
      tags:
      - weighing-devices
      summary: Liefert die vorhandenen Waagen
      description: Liefert eine Liste von Waagen, die im System bekannt sind. Sind keine Waagen verfügbar wird eine leere Liste zurückgegeben.
      parameters:
      - $ref: '#/parameters/pageParam'
      - $ref: '#/parameters/sizeParam'
      - $ref: '#/parameters/sortParam'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/WeighingDevicePage'
    post:
      tags:
      - weighing-devices
      summary: Anlegen einer Waage
      description: Legt eine Waage mit den spezifizierten Daten im System an. Wurde eine ID angegeben, wird die Anfrage mit BAD_REQUEST abgelehnt.
      parameters:
      - in: body
        name: weighing-device
        description: Waagedaten
        required: true
        schema:
          $ref: '#/definitions/WeighingDevice'
      responses:
        '201':
          description: (CREATED) Waage wurde erfolgreich erstellt. Die ID der Waage wird zurückgegeben.
          schema:
            $ref: '#/definitions/CreateResult'
        '400':
          description: (Bad Request) Fehlerhafte Anfragedaten.
          schema:
            $ref: '#/definitions/Error'
  /weighing-devices/{id}:
    put:
      tags:
      - weighing-devices
      summary: Ändern einer Waage
      description: Aktualisiert Daten einer Waage mit den spezifizierten Daten.
      parameters:
        parameters:
        - name: id
          in: path
          description: ID der Waage
          required: true
          type: integer
        - in: body
          name: weighing-device
          description: Waagedaten
          required: true
          schema:
            $ref: '#/definitions/WeighingDevice'
      responses:
        '204':
          description: (UPDATED) Waage wurde erfolgreich aktualisiert. Keine Rückgabe.
        '400':
          description: (BAD_REQUEST) Die angegebene Id im Pfad stimmt nicht mit der Id des Objekts überein oder die übergebene Datenstruktur ist nicht gültig.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: (NOT_FOUND) Zu aktualisierende Waage wurde nicht gefunden.
          schema:
            $ref: '#/definitions/Error'
definitions:
  id:
    description: Identifier einer Ressource
    example: 100001
    type: integer
    format: int64
    minimum: 0
    uniqueItems: true
  CreateResult:
    type: object
    description: Rückgabewert beim Erstellen einer neuen Ressource.
    required:
    - id
    properties:
      id:
        $ref: '#/definitions/id'
  WeighingNote:
    type: object
    required:
    - branch
    - number
    - weighings
    - producer
    - transporter
    - destination
    properties:
      branch:
        $ref: '#/definitions/Branch'
      number:
        description: Wägescheinnummer
        example: '12873472'
        type: number
        format: long
      weighings:
        description: Wägevorgänge
        type: array
        items:
          $ref: '#/definitions/Weighing'
      producer:
        $ref: '#/definitions/Role'
      transporter:
        $ref: '#/definitions/Role'
      destination:
        $ref: '#/definitions/Role'
  Role:
    type: object
    description: Rolle, die empfängt, befördert oder erzeugt.
    properties:
      id:
        description: Id/Nummer
        type: string
      name1:
        description: Firmenname/Kundenname
        type: string
      name2:
        description: Niederlassungsname/Leistungsortbeschreibung/Anlagenname
        type: string
      address:
        $ref: '#/definitions/Address'
  Branch:
    type: object
    description: Niederlassungsdaten
    required:
    - companyName
    - branchName
    - address
    properties:
      id:
        description: Identifier einer Niederlassung
        example: 1
        type: number
      companyName:
        description: Firmenname
        example: REMONDIS GmbH & Co. KG
        type: string
      branchName:
        description: Niederlassungsname
        example: REMONDIS Lünen
        type: string
      address:
        $ref: '#/definitions/Address'
  Weighing:
    type: object
    description: Wägevorgang
    required:
    - scaleData
    - type
    properties:
      scaleData:
        $ref: '#/definitions/WeighingData'
      type:
        description: Art der Wägung. Hier könnte "Erstwägung(first)", "Zweitwägung(second)" oder "Einmalwägung(single)" ausgewählt werden.
        type: string
        example: single
        enum:
        - single
        - first
        - second
  WeighingData:
    type: object
    description: Verwiegung
    required:
    - alibiNumber
    - weight
    - unit
    - timestamp
    properties:
      alibiNumber:
        description: Identifier der Waage
        type: number
        format: long
        example: '7123712'
      weight:
        description: Gewicht
        type: number
        format: float
        example: '13720'
      unit:
        description: Einheit
        type: string
        enum:
        - kg
        - t
      timestamp:
        type: string
        format: YYYY-MM-DDThh:mm:ss.sTZD
        example: '2017-07-16T19:20:30.45+01:00'
  Address:
    type: object
    required:
    - houseNumber
    - street
    - city
    - zipCode
    - countryCode
    properties:
      houseNumber:
        description: Hausnummer; kann auch aus Zeichen bestehen, wie z.B. in '10A'
        type: string
        example: '138'
      street:
        type: string
        example: Brunnenstraße
      city:
        type: string
        example: Lünen
      zipCode:
        type: string
        example: '44536'
      countryCode:
        type: string
        example: DE
        format: ISO 3166
  WeighingDevice:
    type: object
    description: Eine Waage
    required:
    - deviceId
    - name
    - branchIds
    properties:
      id:
        description: Identifier für eine Waage
        type: number
        example: 1
      deviceId:
        description: Referenzidentifier für eine Waage im Fremdsystem
        type: number
        example: 42
      name:
        description: Anzeigename einer Waage
        type: string
        example: Meine Waage
      branchIds:
        type: array
        items:
          type: number
          example: 1
  WeighingDevicePage:
    allOf:
    - $ref: '#/definitions/Page'
    - type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/definitions/WeighingDevice'
  BranchPage:
    allOf:
    - $ref: '#/definitions/Page'
    - type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/definitions/Branch'
  Page:
    type: object
    description: Ergebnisseite einer paginierten Anfrage
    properties:
      number:
        type: number
        description: Die laufende Nummer der gelieferten Seite (0-basiert)
        example: 3
      totalPages:
        type: number
        description: Anzahl verfügbarer Seiten
        example: 3
      size:
        type: number
        description: Die Anzahl Elemente pro Seite
        example: 10
      totalElements:
        type: number
        description: Die Anzahl der verfügbarer Elemente
      numberOfElements:
        type: number
        description: Die konkrete Anzahl Elemente auf dieser Seite (kann von "size" abweichen, z.B. auf der letzten Seite).
        example: 5
      last:
        type: boolean
        description: '"true", wenn es sich um die letzte Seite handelt'
        example: true
      first:
        type: boolean
        description: '"true", wenn es sich um die erste Seite handelt'
        example: false
  Error:
    type: object
    description: Fehlerinformationen im Falle eines aufgetretenen Fehlers
    properties:
      errorCode:
        type: string
        description: Code des aufgetretenen Fehlers
        example: ValidationError
      tracing:
        type: object
        properties:
          traceId:
            type: string
            description: Korrelations-ID, über die dieser Fehler z.B. mit Log-Einträgen korreliert werden kann (eine Erläuterung des Begriffs "trace" ist dem Reference Manual von Spring Cloud Sleuth zu entnehmen)
            example: 71ff6e8b547ea055
          rootCauseSpanId:
            type: string
            description: ID des Spans, in dem der Fehler ursprünglich aufgetreten ist (eine Erläuterung des Begriffs "span" ist dem Reference Manual von Spring Cloud Sleuth zu entnehmen)
            example: 71ff6e8b547ea055
      validationErrors:
        type: array
        items:
          type: object
          properties:
            fieldName:
              type: string
              description: Name des Feldes, dessen Validierung fehlgeschlagen ist
              example: username
            errorCode:
              type: string
              description: Code der Validierung, die fehlgeschlagen ist
              example: NotNull
parameters:
  pageParam:
    name: page
    in: query
    description: Seitennummer
    required: false
    type: integer
    format: int64
  sizeParam:
    name: size
    in: query
    description: Anzahl der Ergebnisse, die angezeigt werden sollen.
    required: false
    type: integer
    format: int64
  sortParam:
    name: sort
    in: query
    description: 'Reihenfolge der Ergebnisse, per Spaltenname. Kann jeweils pro Datenbank-Spalte
      angegeben werden: z.B. sort=name,asc&sort=id,desc'
    pattern: '[a-zA-Z]+(,asc|,desc)?'
    required: false
    type: string
externalDocs:
  description: Zu Gitlab
  url: http://git.remondis-de.local/renew/weighing-service